package com.profitsaathi.seller.aichat;

import jakarta.persistence.*;
import lombok.Data;
import org.hibernate.annotations.CreationTimestamp;

import java.time.LocalDateTime;

@Entity
@Data
@Table(name = "ai_chat_messages", indexes = {
        @Index(name = "idx_aichat_msg_session", columnList = "session_id, id")
})
public class AiChatMessage {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    @Column(name = "session_id", nullable = false)
    private Long sessionId;

    /** USER | ASSISTANT */
    @Column(name = "role", nullable = false, length = 16)
    private String role;

    @Column(name = "content", columnDefinition = "TEXT")
    private String content;

    /** Whether this turn carried an image — true for both user uploads and assistant-generated images. */
    @Column(name = "has_image", nullable = false)
    private boolean hasImage;

    /**
     * Filename of an assistant-generated image saved to the Saathi-images
     * upload directory. Null for user-uploaded images (those are sent only
     * once for analysis and not retained) and for text-only turns. The
     * frontend fetches the bytes via {@code GET /api/v1/ai/saathi/image/{id}}.
     */
    @Column(name = "image_path", length = 256)
    private String imagePath;

    /** {@code image/png} or {@code image/jpeg} — needed for the GET endpoint's response Content-Type. */
    @Column(name = "image_mime", length = 32)
    private String imageMime;

    /** Provider that created this image — for "Generated by NVIDIA / Gemini" labelling. */
    @Column(name = "image_provider", length = 32)
    private String imageProvider;

    /**
     * Provider that produced this assistant text turn (GEMINI / OPENROUTER /
     * NVIDIA). Null on user turns and on old rows from before this field was
     * added. Surfaced in the UI as a tiny "via X" line under the bubble so
     * the seller can see when fallback kicks in.
     */
    @Column(name = "chat_provider", length = 32)
    private String chatProvider;

    @CreationTimestamp
    @Column(name = "created_at", nullable = false, updatable = false)
    private LocalDateTime createdAt;
}
