services:
  app:
    build: .
    container_name: profitsaathi-app
    restart: unless-stopped

    environment:
      SPRING_PROFILES_ACTIVE: uat

      # PostgreSQL Cloud
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      # Redis Cloud
      REDIS_URL: ${REDIS_URL}

      # CORS
      ALLOWED_ORIGINS: ${ALLOWED_ORIGINS}

      # Security
      JWT_SECRET: ${JWT_SECRET}
      AES_SECRET_KEY: ${AES_SECRET_KEY}

      # Mail
      MAIL_HOST: ${MAIL_HOST}
      MAIL_PORT: ${MAIL_PORT:-587}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      MAIL_FROM: ${MAIL_FROM}

      # Razorpay
      RAZORPAY_KEY_ID: ${RAZORPAY_KEY_ID}
      RAZORPAY_KEY_SECRET: ${RAZORPAY_KEY_SECRET}

      # AI
      GOOGLE_AI_API_KEY: ${GOOGLE_AI_API_KEY:-}
      OPENROUTER_API_KEY: ${OPENROUTER_API_KEY:-}

      # API URL
      PUBLIC_API_URL: ${PUBLIC_API_URL}

      LOG_FORMAT: json

    ports:
      - "9090:9097"

    volumes:
      - app_uploads:/app/uploads

  waha:
    image: devlikeapro/waha
    restart: unless-stopped
    ports:
      - "3001:3000"
    volumes:
      - waha_sessions:/app/.sessions

volumes:
  app_uploads:
  waha_sessions:
